"""Database creation

Revision ID: 4f37547c1c05
Revises: 
Create Date: 2023-12-04 12:11:16.152935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f37547c1c05'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_id', table_name='stock')
    op.drop_table('stock')
    op.alter_column('tokentable', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tokentable', 'token_type')
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    op.add_column('user', sa.Column('registered_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'registered_at')
    op.drop_column('user', 'password')
    op.add_column('tokentable', sa.Column('token_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('tokentable', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('stock',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stock_pkey'),
    sa.UniqueConstraint('company', name='stock_company_key')
    )
    op.create_index('ix_stock_id', 'stock', ['id'], unique=False)
    # ### end Alembic commands ###
