"""Double change

Revision ID: a901dfd26fb0
Revises: 56864629f0ba
Create Date: 2023-12-12 02:06:25.907918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a901dfd26fb0'
down_revision: Union[str, None] = '56864629f0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('user', 'balance',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'balance',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('stock', 'price',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
