"""Model update

Revision ID: f5e848217e92
Revises: 128c138224bb
Create Date: 2023-12-11 18:47:12.289602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e848217e92'
down_revision: Union[str, None] = '128c138224bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_stocks', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('stock', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'description')
    op.drop_column('personal_stocks', 'quantity')
    # ### end Alembic commands ###
